// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaFacturacion.Data;

#nullable disable

namespace SistemaFacturacion.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715031330_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaFacturacion.Models.AsientoContable", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsiento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdCuentaContable")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFacturaReferencia")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoDebito")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdAsiento");

                    b.HasIndex("IdCuentaContable");

                    b.HasIndex("IdFacturaReferencia");

                    b.ToTable("AsientosContables");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.AuditoriaLog", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("IdRegistro")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUsuario");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.CatalogoCuentas", b =>
                {
                    b.Property<int>("IdCuentaContable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCuentaContable"));

                    b.Property<string>("NombreCuenta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdCuentaContable");

                    b.ToTable("CatalogoCuentas");

                    b.HasData(
                        new
                        {
                            IdCuentaContable = 1,
                            NombreCuenta = "Caja"
                        },
                        new
                        {
                            IdCuentaContable = 2,
                            NombreCuenta = "Banco"
                        },
                        new
                        {
                            IdCuentaContable = 3,
                            NombreCuenta = "Cuentas por Cobrar"
                        },
                        new
                        {
                            IdCuentaContable = 4,
                            NombreCuenta = "Cuentas por Pagar"
                        },
                        new
                        {
                            IdCuentaContable = 5,
                            NombreCuenta = "Ingresos por Ventas"
                        },
                        new
                        {
                            IdCuentaContable = 6,
                            NombreCuenta = "ITBIS por Pagar"
                        });
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdContrato"));

                    b.Property<string>("Condiciones")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdEntidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdContrato");

                    b.HasIndex("IdEntidad");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entidad", b =>
                {
                    b.Property<int>("IdEntidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEntidad"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdEntidad");

                    b.HasIndex("RncCedula")
                        .IsUnique();

                    b.ToTable("Entidades");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.FacturaCabecera", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FirmaDGII")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdEntidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("Itbis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroECF")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdEntidad");

                    b.HasIndex("NumeroECF")
                        .IsUnique();

                    b.ToTable("FacturasCabecera");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.FacturaDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionItem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdFactura");

                    b.ToTable("FacturasDetalle");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.MovimientosCx", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimiento"));

                    b.Property<string>("ArchivoEvidencia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CategoriaGasto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPendiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NumeroCuota")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int?>("TotalCuotas")
                        .HasColumnType("integer");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdFactura");

                    b.ToTable("MovimientosCx");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.ParametrosEmpresa", b =>
                {
                    b.Property<int>("IdParametro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParametro"));

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PorcentajeITBIS")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("SecuenciaEmpresa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecuenciaFiscalECF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdParametro");

                    b.ToTable("ParametrosEmpresa");

                    b.HasData(
                        new
                        {
                            IdParametro = 1,
                            NombreEmpresa = "Mi Empresa SRL",
                            PorcentajeITBIS = 0.18m,
                            SecuenciaEmpresa = "001",
                            SecuenciaFiscalECF = "ECF001"
                        });
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Permisos")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Administrador",
                            Permisos = "TODO"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "Contador",
                            Permisos = "FACTURAS,REPORTES,MOVIMIENTOS"
                        },
                        new
                        {
                            IdRol = 3,
                            Nombre = "Encargado de facturación",
                            Permisos = "FACTURAS,ENTIDADES"
                        },
                        new
                        {
                            IdRol = 4,
                            Nombre = "Gerente financiero",
                            Permisos = "REPORTES,CONTRATOS,MOVIMIENTOS"
                        },
                        new
                        {
                            IdRol = 5,
                            Nombre = "Cliente",
                            Permisos = "CONSULTA"
                        },
                        new
                        {
                            IdRol = 6,
                            Nombre = "Proveedor",
                            Permisos = "CONSULTA"
                        });
                });

            modelBuilder.Entity("SistemaFacturacion.Models.User", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Activo = true,
                            Email = "admin@sistema.com",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdRol = 1,
                            NombreCompleto = "Administrador del Sistema",
                            PasswordHash = "$2a$11$4bEImu8PNaPhgHS2iQM8YOg1gubP0uFTqDOxh8QgedWuMvs1WYMma"
                        });
                });

            modelBuilder.Entity("SistemaFacturacion.Models.AsientoContable", b =>
                {
                    b.HasOne("SistemaFacturacion.Models.CatalogoCuentas", "CuentaContable")
                        .WithMany("Asientos")
                        .HasForeignKey("IdCuentaContable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaFacturacion.Models.FacturaCabecera", "FacturaReferencia")
                        .WithMany()
                        .HasForeignKey("IdFacturaReferencia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CuentaContable");

                    b.Navigation("FacturaReferencia");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.AuditoriaLog", b =>
                {
                    b.HasOne("SistemaFacturacion.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Contrato", b =>
                {
                    b.HasOne("SistemaFacturacion.Models.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("IdEntidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entidad");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.FacturaCabecera", b =>
                {
                    b.HasOne("SistemaFacturacion.Models.Entidad", "Entidad")
                        .WithMany("Facturas")
                        .HasForeignKey("IdEntidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entidad");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.FacturaDetalle", b =>
                {
                    b.HasOne("SistemaFacturacion.Models.FacturaCabecera", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.MovimientosCx", b =>
                {
                    b.HasOne("SistemaFacturacion.Models.FacturaCabecera", "Factura")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.User", b =>
                {
                    b.HasOne("SistemaFacturacion.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.CatalogoCuentas", b =>
                {
                    b.Navigation("Asientos");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Entidad", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.FacturaCabecera", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SistemaFacturacion.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
